{% set goname = "github.com/direnv/direnv" %}
{% set version = "2.34.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 3d7067e71500e95d69eac86a271a6b6fc3f2f2817ba0e9a589524bf3e73e007c

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go build -v -ldflags "-X main.revision=conda-forge" . -o $PREFIX/bin/direnv  # [osx and arm64]
    - go install -v -ldflags "-X main.revision=conda-forge" .  # [not (osx and arm64)]


requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - direnv --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: unclutter your .profile

extra:
  recipe-maintainers:
    - daizeng1984
    - wolfv
