{% set goname = "github.com/direnv/direnv" %}
{% set version = "2.29.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: a0ceb76a58a6ca81a8669a9ef2631fbad41d7c1a27cc0ec738c71c6d71f9751f

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v -ldflags "-X main.revision=conda-forge" .

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - direnv --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: unclutter your .profile

extra:
  recipe-maintainers:
    - daizeng1984
