{% set goname = "github.com/direnv/direnv" %}
{% set version = "2.35.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: a7aaec49d1b305f0745dad364af967fb3dc9bb5befc9f29d268d528b5a474e57

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go build -v -ldflags "-X main.revision=conda-forge" -o $PREFIX/bin/direnv  # [osx and arm64]
    - go install -v -ldflags "-X main.revision=conda-forge" .  # [not (osx and arm64)]
    - go-licenses save . --save_path={{ SRC_DIR }}/license_files || true


requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses >=1.0.0

test:
  commands:
    - direnv --version

about:
  home: https://{{ goname }}
  license: MIT
  license_family: MIT
  license_file:
    - {{ pkg_src }}/LICENSE
    - license_files/
  summary: unclutter your .profile

extra:
  recipe-maintainers:
    - daizeng1984
    - wolfv
