context:
  name: direnv
  version: "2.37.0"

package:
  name: ${{ name|lower }}
  version: ${{ version|replace("-", "_") }}

source:
  - target_directory: src
    url: https://github.com/direnv/direnv/archive/v${{ version }}.tar.gz
    sha256: 6302f3eb824ae5f7d33475c6e9ac0ec46a228e282fca7dba881f3536575a25c8

build:
  number: 0
  script:
    - pushd src
    - if: osx and arm64
      then:
        - go build -v -ldflags "-X main.revision=conda-forge" -o $PREFIX/bin/direnv
      else:
        - go install -v -ldflags "-X main.revision=conda-forge" .
    - go-licenses save . --save_path=${{ SRC_DIR }}/license_files || true


requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses

tests:
  - script:
      - direnv --version

about:
  homepage: https://github.com/direnv/direnv
  license: MIT
  license_file:
    - src/LICENSE
    - license_files/
  summary: unclutter your .profile

extra:
  recipe-maintainers:
    - daizeng1984
    - wolfv
